name: BlueMap-Quests
main: org.browsit.bluemapquests.BlueMapQuests
version: 1.1
api-version: 1.13
description: Display Quests information on BlueMap maps
author: Browsit
depend: [BlueMap, Quests]
soft-depend: [Citizens, WorldGuard]